### ISSUE TITLE
[question] is this project ready to work?

### ISSUE THREAD

**Issue by zprjk** [bohoffi/ngx-score#9]
Title. if not maybe a disclaimer

**Comment by bohoffi** [comment]
@zprjk first of all thank you for your interest :)
This project is at a very early stage but if you want to you could try is.

Fell free to open issues if you find something bad.

**Comment by zprjk** [comment]
Thx. I'm interesting making a solution that displays the sheet from musicxml and also other custom features like cursor, note/bar highlights. Went to demo page to quickly check musicxml parse https://bohoffi.github.io/ngx-score but got nothing.

**Comment by bohoffi** [comment]
That's because the MusicXML parsing ins't ready yet.
But if I understand your requirements correctly you can use the following project:
[OSMD](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay)
The MusicXML rendering is implemented in a far more complete state.
